# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Fallingfunctions',
                'doc_host': 'https://lnicole08.github.io',
                'git_url': 'https://github.com/lnicole08/Fallingfunctions',
                'lib_path': 'Fallingfunctions'},
  'syms': {'Fallingfunctions.core': {'Fallingfunctions.core.foo': ('core.html#foo', 'Fallingfunctions/core.py')}}}